### ISSUE TITLE
Unable to create a docker container (X server + wine)

### ISSUE THREAD

**Issue by ABeltramo** [nwjs-community/nw-builder#295]
I wan't to create a Docker container to build my app on an headless server online (Ubuntu server). I tried lot of solutions but no one function.
The main problem here it's the wine application that without an X server can't update the exe file!
I'll share what I created so far:

```
FROM ubuntu:14.04

# Installing wine for windows icon and git
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN dpkg --add-architecture i386 
RUN add-apt-repository ppa:wine/wine-builds
RUN apt-get update && apt-get install --install-recommends -y \
  winehq-devel \
  git \
  curl

# Installing nodejs
RUN curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
RUN apt-get install -y nodejs

#Putting mono in wine folder
RUN mkdir /root/.wine/
RUN mkdir /root/.wine/mono
RUN curl -o /root/.wine/mono/wine-mono-4.6.0.msi http://dl.winehq.org/wine/wine-mono/4.6.0/wine-mono-4.6.0.msi

# Headless wine config
# Don't work... :(
RUN apt-get install -y Xvfb
#RUN Xvfb :1 &
#RUN export DISPLAY=:1
#RUN sleep 4

# Start wine config
#RUN DISPLAY=:1 wine wineboot --init

# Copy current folder and files
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app
# Installing nwbuilder dependency
RUN npm install

CMD [ "sh", "start.sh" ]
```

Where start.sh just git clone and start node webkit builder.

**Comment by Klemen1337** [comment]
So what is the solution?

**Comment by adam-lynch** [comment]
@Klemen1337 to be honest, I don't know. I've never had to do what's desired here. This sounds like it might be worth opening an issue with wine about?

If anyone knows how to solve this, please chime in 😄

**Comment by Klemen1337** [comment]
@adam-lynch I switched to nwjs-builder-phoenix and it works like a charm :smile:. They also use wine and its fine.

**Comment by adam-lynch** [comment]
Oh... @evshiron do you know what's needed to solve this? 😄

**Comment by evshiron** [comment]
Hmmm? `nwjs-builder` used to test in Travis CI and the [.travis.yml](https://github.com/evshiron/nwjs-builder/blob/master/.travis.yml) was copied from somewhere to enable testing built NW.js apps headlessly, but `nwjs-builder-phoenix` hasn't been tested in these environments yet.

By the way, `nw-builder` uses `winresourcer` to accomplish resource editing, while `nwjs-builder` uses `node-resourcehacker` and `nwjs-builder-phoenix` uses `node-rcedit`.
These tools should have been discussed before, and I switched to `node-rcedit` because it's open source and focused on this task for Electron apps, and it doesn't have a GUI.
