### ISSUE TITLE
Downloading cache failed

### ISSUE THREAD

**Issue by libook** [nwjs-community/nw-builder#364]
I love nwjs.
I'm living in China. And the network is sh*t because of GFW.
Is there a solution?
May I choose another download source?
Or download cache by hand?

**Comment by rogerwang** [comment]
https://cnpmjs.org/mirrors/nwjs/

**Comment by libook** [comment]
Would you please show me how to configure it?

**Comment by DblK** [comment]
I'm not familiar with China network, but you can try to override the "downloadUrl" option and specify the above url.

If it doesn't work you can create by hand the cache folder that contain all downloaded version.
Keep me posted if the first solution works for you. If not I will detail the second one.

**Comment by adam-lynch** [comment]
As far as I remember, the `downloadUrl` option doesn't work for versions >=0.12.3 or else >0.12.3. We'll make sure there's a way to do this and specifically mention cnpm in the documentation. Thanks for reporting.

**Comment by adam-lynch** [comment]
@dblk I see you assigned yourself. See #355 which does some of what's needed.

But @rogerwang there's no mirror for http://nwjs.io/versions.json right?

**Comment by rogerwang** [comment]
right.

**Comment by julmot** [comment]
One question regarding this issue: Why is it downloading sdk files all the time? If I run nwbuild without `-r` and with `-r` after, I expect that it cached the files already. But it still downloads sdk files.

**Comment by adam-lynch** [comment]
@julmot sounds like a separate bug

**Comment by keyiis** [comment]
@adam-lynch Could add property "mirror" to options?like:
```
 new NwBuilder({
        mirror:'https://npm.taobao.org/mirrors/nwjs/',
        flavor:process.env.NODE_ENV == 'production' ? 'normal':'sdk',
        platforms: ['win32']
    });
```

**Comment by superyanggx** [comment]
put the package [nwjs-sdk-v0.14.7-win-ia32.zip] at cache dir, it works. cache dir like "D:\xiaobao-nw\node_modules\_nw-builder@3.5.7@nw-builder\cache\0.14.7-sdk" and sub dir is "win32" if it is on window, so the full path="D:\xiaobao-nw\node_modules\_nw-builder@3.5.7@nw-builder\cache\0.14.7-sdk\win32" with package nwjs-sdk-v0.14.7-win-ia32.zip

**Comment by superyanggx** [comment]
put the package [nwjs-sdk-v0.14.7-win-ia32.zip] at the cache dir, it works.
cache dir like "D:\xiaobao-nw\node_modules_nw-builder@3.5.7@nw-builder\cache\0.14.7-sdk" and sub dir is "win32" if it is on window, so the full path is "D:\xiaobao-nw\node_modules_nw-builder@3.5.7@nw-builder\cache\0.14.7-sdk\win32" with package nwjs-sdk-v0.14.7-win-ia32.zip

**Comment by CosmoMyzrailGorynych** [comment]
I will copycat my findings for further readers:

To download NW.js binaries from a different place (for example, from live builds), do the following:

1) Publish a customNwManifest.json with the needed version as its `latest` one, as well as listed in `versions`. Create a variable `nwManifest` with an URL pointing to this file.
   See https://nwjs.io/versions.json as an example.
2) Set `nwSource` variable to the directory with a folder for this version.
   For example, if your binaries for each platform are at
   https://dl.nwjs.io/live-build/nw50/20201223-162000/6a3f52427/v0.50.3/,
   then you should specify the URL
   https://dl.nwjs.io/live-build/nw50/20201223-162000/6a3f52427/.
3) Set `nwVersion` variable to `undefined` so that nw-builder loads the needed version from the created manifest and downloads it from a given source.

For some reason, setting `nwVersion` to a specific version doesn't work, even with a custom manifest.

Also, note that you may need to clear the `ct-js/cache` folder.

Then you will run:
```js
const nw = new NwBuilder({
    version: nwVersion,
    downloadUrl: nwSource,
    manifestUrl: nwManifest
});
```
