### ISSUE TITLE
Option to generate zipped package

### ISSUE THREAD

**Issue by Helidium** [nwjs-community/nw-builder#366]
It would be nice to have an option like zipAsPackage that would generate package.nw. Currently only merge or copy exists as I am aware...

**Comment by DblK** [comment]
Can you describe a little bit more about the package.nw?

Thanks

**Comment by matthew-dean** [comment]
I just came here to suggest this very thing. Right now, when you choose `zip: false`, it leaves the plain files in the same directory as the executable. It loads fast, which is great, but it leaves the file organization a little cluttered. NW.js actually has built-in support for a special folder name. See: http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#package-option-1-plain-files-recommended

You can put files in a `package.nw` folder (Windows/Linux) or a `app.nw` within `nwjs.app/Contents/Resources/` on Mac.

So, when choosing `zip: false`, it would be great if the `*.nw` folder was generated, rather than dumping into the executable directory. (I think that's better than another `zipAsPackage` option as there's no inherent advantage to a more cluttered app directory.)

Note in the supplied link that this is the recommended method for packaging, despite the fact that, for whatever reason, nw-builder's default option is to zip, even though that leads to terrible performance on Windows.

**Comment by adam-lynch** [comment]
There are so many different ways people want the files zipped, not zipped, merged with executable, etc. I don't know what we should do. It wouldn't surprise me if we ended up redoing the options around this stuff.

@matthew-dean devil's advocate: you only want this because it makes your `Resources` cleaner? In the off-chance that changing it to this could break someone's app (I doubt it), is it worth it?

**Comment by adam-lynch** [comment]
I'm going to close this optimistically (I'm doing a bit of a triage now). Please let me know if it's still needed. If so, please describe why it would be useful to have a `package.nw`. Thanks

Note: you can also tweak the compression levels of the zip, etc. using the [`zipOptions` option](https://github.com/nwjs-community/nw-builder#optionszipoptions)

**Comment by hgouveia** [comment]
for some reason it seems that windows is removing the nwjs content from the %TEMP% really frequently (around 1h) , probably a new windows update?,  so have the need to stop using the zip option but now all files are copied in the same folder messing around the files , this of course wont break anything, 

but is important to have things organize, at least to have the option to put those files inside `package.nw` folder, and not an opinionated  way, we have documentation already with some other folder/files included in the root of the project,  were we lead the user , and now is messy to find those files to the users, and yeap we can update this, but i would like to keep the app as clean as possible if i have the choice . Thanks!
