### ISSUE TITLE
the 'flavor' option not work when cached versions exist

### ISSUE THREAD

**Issue by turnerguo** [nwjs-community/nw-builder#382]
e.g. when I run the example there will be a 'cache' folder with downloaded nw sdk versions.
after change 'flavor' to 'normal', run gulp again it does no effect actually, I guess it just check the 'cache' folder but not check with 'flavor' changes.

**Comment by adam-lynch** [comment]
hmm I tested this. @DblK have you seen this?

**Comment by nurishi** [comment]
I just realized this is actually happening to me in normal build.

I guess this is due to the file count check in downloader.js. Normal build seems to contain only 2 files(checked with 0.14.7 and 0.19.2). This explains why it works on sdk but not on normal.

Just changing the count here from 3 to 2 worked for me.
https://github.com/nwjs/nw-builder/blob/3.1.3/lib/downloader.js#L27

**Comment by adam-lynch** [comment]
This should've been fixed in 3.2.3. Please update, delete your cache directory, and try again.

@nurishi that sounds like a separate problem. Open another issue if it's still a problem please
