### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by adam-lynch** [nwjs-community/nw-builder#447]
Add greenkeeper preferably. Edit: it's already hooked up but broken possibly. Need to more a few PRs too... depends on #446.

**Comment by bastimeyer** [comment]
Thanks, @adam-lynch, for spending some time on this project again. 👍 

Since you're intending to upgrade the dependencies, could you please take a look at the `temp` dependency? This one is causing an annoying deprecation message on newer node versions.

If you run `node --trace-deprecation ...`, you can see that it's coming from there.
This has already been fixed in a newer version two years ago, but the dependency doesn't seem to be maintained anymore, so maybe you want to take a look at another one, if it's necessary.

```
(node:12673) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
  at Object.<anonymous> (/home/basti/foo/node_modules/temp/lib/temp.js:170:45)
```

**Comment by adam-lynch** [comment]
Will do thanks

**Comment by adam-lynch** [comment]
> This one is causing an annoying deprecation message on newer node versions.

@bastimeyer like what? I don't see it when using Node 6.10.3

**Comment by bastimeyer** [comment]
> like what?

The one I already posted:
`DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

> Node 6.10.3

This has been deprecated in node 7:
https://github.com/nodejs/node/pull/6739

**Comment by adam-lynch** [comment]
I meant which version. Thanks.
