### ISSUE TITLE
Replacing application source code files for delta updates

### ISSUE THREAD

**Issue by vinaynb** [nwjs-community/nw-builder#460]
I am trying to figure out implementing auto updates for nw.js application and at the moment i am on linux/ubuntu. I am building my app named 'nw-autoupdater-demo' using sdk flavor of nw.js binary and it creates a folder with all the files inside it which looks something like this
![screenshot from 2017-07-17 18 07 35](https://user-images.githubusercontent.com/1573465/28268168-d971dd22-6b1a-11e7-84b2-02862a6e6b34.png)

I am using nw-autoupdater to roll out my updates and i do not wish to send nw.js binary everytime user needs to update to a newer version because the changes are related to just my js/html/css source code only. So i figured out if there's a specific file that contains my application code which i can replace with a newer version and keep the rest of nw.js binaries intact then that would solve my issue.

But from the above figure i cannot figure out which file contains my application code. I tried replacing the main executable file `nw-autoupdater-demo` with a changed version of my code in a older build created using nw-builder and it works !

Is this the correct approach to make changes to the app and issue updates ?
Is the main executable file the only file i need to replace to update my application source and it would just work ?

**Comment by vinaynb** [comment]
@adam-lynch can you shed some light on my query ?

**Comment by adam-lynch** [comment]
This stuff is really interesting but I'm afraid I can't help much. I'm not sure about Linux I'm sorry :/, I'm not sure where your source goes. Even on Windows & Mac this is tricky because it can trigger the OS / anti-virus, especially if your app is signed. Electron does it nicely (only for Mac & Windows). I think people usually go down the route of publishing their app to package managers instead (e.g. using AppImage or something) rather than having an auto-updater with delta updates. Maybe you could build two simple apps and compare the output to see which files depend on your source?

**Comment by Blatman** [comment]
Quite an old issue this but when I have been messing around with builds on Linux I tend to use the unzipped option in NWB and this creates a package.nw folder alongside all the files in the snapshot above and it is this folder that holds all the app files. I would have thought that if I used the auto-updater to update the app alone then all I would need to do is replace the package.nw folder.
A separate package.nw folder will of course increase the size of the overall distro build.
Cheers,
Blane
