### ISSUE TITLE
NPM audit reports nw-builder as insecure

### ISSUE THREAD

**Issue by ea2973929** [nwjs-community/nw-builder#500]
See https://david-dm.org/nwjs/nw-builder

The problematic package is `lodash` and there are new versions available that can easily fix this.

`npm audit` with even low security problems will fail our builds (because npm audit does not distinguish between different levels) so an updated nw-builder would be very welcome.

**Comment by kessler** [comment]
@ea2973929 I looked into this. It seems there is a potential for breaking changes as a result of the update. If you could submit a PR it would be great.

**Comment by vankasteelj** [comment]
This seems pretty straightforward:

- platform-overrides is no longer maintained (4 years since last commit)
- platform-overrides is only a small package (117 lines that could easily be reduced to 50 or so) hence it could be ported into nw-builder code (either a complete rewrite, or a copy/paste with one or two tweaks and the MIT license in commentary)
- that wouldnt hurt the oss community as nothing depends on it except for nw-builder (and similar nwjs-oriented builders)

**Comment by kessler** [comment]
@vankasteelj could you submit a PR ?

**Comment by vankasteelj** [comment]
Yeah probably, but idk when I'll have the time, monday maybe

**Comment by vankasteelj** [comment]
if @adam-lynch is there, https://github.com/adam-lynch/platform-overrides/pull/6 

I'll PR a port to nw-builder as well

**Comment by vankasteelj** [comment]
Ok, PR done
